export DOTFILES_PATH="/Users/aLucaz/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export DOTLY_THEME="codely"
export ZIM_HOME="$DOTFILES_PATH/shell/zsh/.zim"
export NAVI_PATH="$DOTFILES_PATH/doc/navi"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.17.jdk/Contents/Home"
. "$HOME/.cargo/env"
